### ISSUE TITLE
how to Execute command and quit

### ISSUE THREAD

**Issue by denefer** [dbcli/mssql-cli#298] opened 2019-09-18 06:24 UTC
hi all:

how to use mssql-cli command to show like "mysql -e 'show databases'"

**Comment by jeffhongxiao** [comment] 2019-09-18 19:30
maybe related: https://github.com/dbcli/mssql-cli/issues/139#issuecomment-531748110

**Comment by pensivebrian** [comment] 2019-09-19 22:16
This is one the roadmap, but there is not ETA adding this.

**Comment by pensivebrian** [comment] 2019-09-30 21:47
Closing as a duplicate of https://github.com/dbcli/mssql-cli/issues/242, which will be used to track this issue.

**Closed by pensivebrian** 2019-09-30 21:47 UTC
