### ISSUE TITLE
A query is already in progress for this editor session

### ISSUE THREAD

**Issue by zayscue** [dbcli/mssql-cli#95] opened 2017-12-13 05:21 UTC
I'm running the latest release on windows 10 and when every I try to run a query on either single or multi line mode the only message I get is as follows, "A query is already in progress for this editor session. Please cancel this query or wait for its completion."  The problem is that I don't no other queries running.

**Comment by MrMeemus** [comment] 2017-12-13 17:14
@zayscue what kind of Server and DB are you targeting?

**Comment by zayscue** [comment] 2017-12-13 17:22
Microsoft SQL Server 2014 - 12.0.4100.1 (X64)   Apr 20 2015 17:29:27   Copyright (c) Microsoft Corporation  Developer Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor)

**Comment by MrMeemus** [comment] 2017-12-13 19:17
I was able to repro this issue, it seems to be some concurrency issue from the back end. Will investigate more. Thanks @zayscue !

**Comment by MrMeemus** [comment] 2018-01-24 17:54
Dug a little deeper into this issue. It seems to be because the same mssqlcliclient is being used for completion refresher which may return results slowly. This can lead to the message you are seeing. This was originally by design but after fiddling with slower connections to DB's like Azure it seems like we should probably create a separate connection for the completion refresher. Will update this thread after further discussion.

**Comment by kabirbaidhya** [comment] 2018-01-30 06:48
I keep getting this issue too frequently almost every time I run query on a remote server. Do we have a plan of when this bug is going to get fixed and released?

**Comment by MrMeemus** [comment] 2018-01-30 16:08
@kabirbaidhya, I will be looking into this fix either late this week or early next week.

**Comment by MrMeemus** [comment] 2018-02-09 02:04
This issue has been fixed in #161. It should be available in our next release (0.10.0) ETA week of Feb 12th.

**Closed by MrMeemus** 2018-02-09 02:04 UTC
Labels: bug
