### ISSUE TITLE
Stored procedure reporting multiple result-sets are not displayed in mssql-cli results

### ISSUE THREAD

**Issue by sethusrinivasan** [dbcli/mssql-cli#129] opened 2017-12-27 00:59 UTC
1) Create a database test1
2) Create  following stored proc
CREATE OR ALTER PROC sp_test_multiple_results
AS
BEGIN
SELECT TOP 10 name,object_id from sys.objects
SELECT TOP 10 name,object_id from sys.columns
END

3) run mssql-cli and execute this proc

**Outcome:**
Only first result set is displayed
mssql-cli
![image](https://user-images.githubusercontent.com/3907049/34367290-9bd2ad76-ea5d-11e7-8f41-d0f779f6543e.png)

**Expected:**
All resultsets to be displayed to user and should be consistent with other tools like SSMS / sqlcmd

SSMS:
![image](https://user-images.githubusercontent.com/3907049/34367302-c9e3ab02-ea5d-11e7-8198-9d73554d722a.png)

sqlcmd:
![image](https://user-images.githubusercontent.com/3907049/34367306-fbc25538-ea5d-11e7-8968-7ee2da98b163.png)

**Comment by abhisheksinha89** [comment] 2017-12-28 22:21
Will look into this

**Comment by abhisheksinha89** [comment] 2018-01-02 22:30
Found the root cause of this issue, working on a fix

**Comment by abhisheksinha89** [comment] 2018-01-03 00:19
@pensivebrian @sethusrinivasan : Above PR to fix this issue

**Comment by abhisheksinha89** [comment] 2018-01-09 22:35
This should be fixed in 0.9.0 and later

**Closed by abhisheksinha89** 2018-01-09 22:35 UTC
Labels: bug
